#==============================================================================
MAKEFLAGS += --silent
run:
	javac $(wildcard *.java)
	java Source $(args)
clean: 
	$(RM) *.class templates/node/*.class templates/list/*.class templates/tree/*.class
#==============================================================================
