#!/bin/bash
CSCOPE_CENTRAL_DB="$HOME/.cscope.d/"
CSCOPE_CURRENT_PATH="$CSCOPE_CENTRAL_DB$(echo $PWD | cut -c 2- | tr / _)"
CSCOPE_TARGET="$CSCOPE_CURRENT_PATH/cscope.files"
 
run_cscoper() {
    find "$PWD" -name '*.[ch]' \
        -o -name '*.java' \
        -o -name '*.cpp' \
        -o -name '*.cc' \
        -o -name '*.hpp' \
        -o -name '*.hh' \
        -o -name '*.py' \
        -o -name '*properties' > $CSCOPE_TARGET
    export CSCOPE_DB="$CSCOPE_CURRENT_PATH/cscope.out"
    cscope -b -i $CSCOPE_TARGET
}

if [ ! -d "$CSCOPE_CENTRAL_DB" ]; then
    echo 'central cscope directory does not exist; creating one now'
    mkdir "$CSCOPE_CENTRAL_DB"
fi

if [ ! -d "$CSCOPE_CURRENT_PATH" ]; then
    mkdir $CSCOPE_CURRENT_PATH
    run_cscoper
else
    echo 'cscope db for project detected; rebuild?'
    while true; do
        read -p 'Y/N ' input
        case $input in
            [Yy] ) run_cscoper; break;;
            [Nn] ) exit;;
            * ) echo 'enter Y or N';;
        esac
    done
fi
